seed: 7

# runtype: train
runtype: test

# model_freeze: False
model_freeze: True
path_to_outputs: /scratch_net/ken/mcrespo/proj_marina/logs_new/inf_embedding_val_noise

# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_12_04/2024-12-07_12h26m33s/checkpoints/epoch_0599.pt # 5 vol normal training
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_12_12/2024-12-12_15h18m48s/checkpoints/epoch_0499.pt # 5 vol meta-learning training
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_12_10/2024-12-14_10h44m19s/checkpoints/epoch_0199.pt # 15 vol training embedding size 256
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_12_12/2024-12-16_10h39m41s/checkpoints/epoch_0499.pt # Meta-learning trained w 4 freeze groups
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs/multivol_12_12/2024-12-16_10h31m46s/checkpoints/epoch_0499.pt # Meta learning trained w v2  
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_26/2025-01-02_11h00m16s/checkpoints/epoch_0199.pt # Model trained on 20 volumes
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_26/2025-01-08_07h23m42s/checkpoints/epoch_0099.pt # Model trained on 30 vols
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_26/2025-01-08_22h13m56s/checkpoints/epoch_0099.pt # Model trained on 50 volumes
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_01_10_train/2025-01-10_20h50m37s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_01_10_train/2025-01-14_18h48m12s/checkpoints/epoch_0199.pt # embedding size 1024 
model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_01_10_train/2025-01-14_18h49m51s/checkpoints/epoch_0199.pt # embedding size 512 dimension
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_02_06_train/2025-02-06_15h59m38s/checkpoints/epoch_0499.pt # L2 regularization (gamma:0.01, LR: 5.e-6)
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_02_06_train/2025-02-08_16h00m41s/checkpoints/epoch_0499.pt # L2 regularization (gamma:0.001, LR: 0,0001)
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/train_sine_embd/2025-02-11_19h47m21s/checkpoints/epoch_0199.pt # Sinusoidal embeddings
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/train_sine_embd/2025-02-12_10h26m03s/checkpoints/epoch_0199.pt # Sinusoidal embeddings w regularization (gamma: 0.01, LR: 5.e-5)
# model_checkpoint:  /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_02_06_train/2025-02-21_22h26m27s/checkpoints/epoch_0199.pt #L2 regularization (gamma 0.01, LR: 5.e-6, 1024, 512)


# Figures output
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/inf_embedding_val/2025-02-20_19h07m24s/checkpoints/epoch_0999.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/inf_embedding_val/2025-02-20_19h03m56s/checkpoints/epoch_0999.pt

dataset:
  # path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Origina/fastMRI/brain/multicoil_train/
  path_to_data:  /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_val/
  n_volumes: 4
  n_slices: 2
  with_mask: True  # NOTE: During training phase, set to False.
  with_center: False
  acceleration: 4
  center_frac: 0.15

dataloader:
  # batch_size: 240_000
  batch_size: 60_000
  pin_memory: False

model:
  id: Siren
  params:
    coord_dim: 3
    vol_embedding_dim: 512
    coil_embedding_dim: 256
    hidden_dim: 512
    n_layers: 8
    L : 10

loss:
  id: MSEL2
  params:
    gamma: 0.0
    sigma: 0.1

optimizer:
  id: Adam
  params:
    lr: 5.e-6 # The dot is necessary, otherwise the parser will mistake this for a string (and not a float).

scheduler:
  id: StepLR
  params:
    gamma: 1.0
    step_size: 20_000

# Training Process
n_epochs: 2000
log_interval: 50
checkpoint_interval: 2000  # Keep in mind that each checkpoint takes ~241 MB of space.

meta_learning:
  reinit_step: 200
  epsilon: 0.01

# ###################################################
# # INFORMATION ONLY - NO EFFECT ON RUN
# ###################################################
# # The following section is for documentation purposes only.
# # It does not affect the actual behavior of the run.
# # These values are used solely for Tensorboard output, to help identify run types.
hparam_info:
  # embedding_vol: 1024
  # embedding_coil: 512
  dropout: False