seed: 7

# runtype: train
runtype: test

# hash_freeze: True
hash_freeze: False
path_to_outputs: /scratch_net/ken/mcrespo/proj_marina/logs_new/inf_embedding_val

# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_23/2025-01-04_14h04m40s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_23/2025-01-08_08h05m32s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_23/2025-01-08_08h05m32s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_23/2025-01-10_20h46m31s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/multivol_12_23/2025-01-12_14h20m17s/checkpoints/epoch_0499.pt
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/train_hash/2025-01-20_00h34m04s/checkpoints/epoch_0599.pt # HASH 10 Features/ pixel, 15 levels
model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/train_hash/2025-01-22_10h57m46s/checkpoints/epoch_0599.pt # HASH 5 Features/ pixel, 15 levels


embedd_init: mean
# embedd_init: reinit
# embedd_init: same_vector

dataset:
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_val/
  n_volumes: 4
  n_slices: 2
  with_mask: True  # NOTE: During training phase, set to False.
  acceleration: 4
  center_frac: 0.15

dataloader:
  batch_size: 120_000
  pin_memory: False

model:
  id: Siren
  params:
    coord_dim: 4
    hidden_dim: 512
    levels: 15
    n_features: 5
    n_min: 45
    size_hashtable: 12
    n_layers: 8

loss:
  id: MSEL2
  params:
    gamma: 0.0
    sigma: 0.1

optimizer:
  id: Adam
  params:
    lr: 5.e-6 # The dot is necessary, otherwise the parser will mistake this for a string (and not a float).

scheduler:
  id: StepLR
  params:
    gamma: 1.0
    step_size: 20_000

# Training Process
n_epochs: 1000
log_interval: 50
checkpoint_interval: 1000  # Keep in mind that each checkpoint takes ~241 MB of space.

meta_learning:
  reinit_step: 2000
  epsilon: 0.01

###################################################
# INFORMATION ONLY - NO EFFECT ON RUN
###################################################
# The following section is for documentation purposes only.
# It does not affect the actual behavior of the run.
# These values are used solely for Tensorboard output, to help identify run types.
hparam_info:
  # dataset: "undersampled (except center)"
  embedding_dim: hash_nomodel