seed: 7

path_to_outputs: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_figures # TODO: SET.

## FULLY SAMPLED
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-10_10h04m05s/checkpoints/epoch_0999.pt # fully sampled 05
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-10_10h04m44s/checkpoints/epoch_0999.pt # FULLY SAMPLED 09
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-10_10h07m22s/checkpoints/epoch_0999.pt # FULLY SAMPLED 21

# UNDERSAMPLED
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-09_10h34m/checkpoints/epoch_1999.pt # 05
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-09_10h35m/checkpoints/epoch_1999.pt # 09
model_checkpoint:  /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hash/02-09_10h31m/checkpoints/epoch_1999.pt # 21

dataset:
  # path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_203_6000861.h5 # TODO: SET.
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_205_2050021.h5
  n_slices: 3
  with_mask: True
  mask_type: Random
  acceleration: 4
  center_frac: 0.15

dataset_full:
  # path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_203_6000861.h5 # TODO: SET.
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_205_2050005.h5
  n_slices: 4
  with_mask: False
  center_frac: 0.15

dataloader:
  batch_size: 120_000
  pin_memory: False
  
model:
  id: SirenHash
  params:
    hidden_dim: 512
    levels: 6
    n_min: 45
    size_hashtable: 12
    n_features: 3
    n_layers: 6

loss:
  id: MSE
  params:
    gamma: 1 # Scalar value that gets multiplied to the real loss value

optimizer:
  id: Adam
  params:
    lr: 5.e-5 # The dot is necessary, otherwise the parser will mistake this for a string (and not a float).
    # weight_decay: 0.1

scheduler:
  id: StepLR
  params:
    gamma: 0.1
    step_size: 20_000

# Training Process
n_epochs: 1
log_interval: 1
checkpoint_interval: 1000

l_pisco:
  addpisco: False
  # addpisco: False
  E_epoch: 1200
  alpha: 1.e-6 # Regularizer for the W
  factor: 0.01 # How much the Lpisco loss gets weighted
  minibatch: 2000
  patch_size: 9

###################################################
# INFORMATION ONLY - NO EFFECT ON RUN
###################################################
# The following section is for documentation purposes only.
# It does not affect the actual behavior of the run.
# These values are used solely for Tensorboard output, to help identify run types.
hparam_info:
  # dataset: "undersampled (except center)"
  dataset: "all data (except center)"

  # observation_type: "train sample"
  observation_type: "test sample"

  # regularization: "None"
  # regularization: "layer norm"
  # regularization: "weight norm"
  # regularization: "AdamW (weight decay)"

  coord_encoding: "positional encoding L=15"
  # coord_encoding: "fourier_feat"

  # normalization: "None"
  normalization: "divide by .999 abs quantile"
  # normalization: "divide by max modulus"
  # normalization: ".05 / .95 real and imag parts"
  # normalization: "min/max real and imag parts"