seed: 7

path_to_outputs: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_hdr/ # TODO: SET.
## FULLY SAMPLED
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-11_21h27m40s/checkpoints/epoch_0999.pt # fully sampled 05
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-11_21h29m09s/checkpoints/epoch_0999.pt # FULLY SAMPLED 09
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-11_21h31m49s/checkpoints/epoch_0999.pt # FULLY SAMPLED 21
# 
# UNDERSAMPLED
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-07_11h44m/checkpoints/epoch_0999.pt # 05
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-07_11h45m/checkpoints/epoch_0999.pt # 09
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco/02-07_11h49m/checkpoints/epoch_0999.pt # 21

## PISCO
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco_new/02-20_19h27m44s/checkpoints/epoch_0999.pt # 05
# model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco_new/02-22_09h29m40s/checkpoints/epoch_0999.pt # 09
model_checkpoint: /scratch_net/ken/mcrespo/proj_marina/logs_new/singlevol_pisco_new/02-19_16h49m25s/checkpoints/epoch_0999.pt # 21

dataset:
  # path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_203_6000861.h5 # TODO: SET.
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_205_2050021.h5
  n_slices: 3
  with_mask: True
  mask_type: Random
  acceleration: 4
  center_frac: 0.15

dataset_full:
  # path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_203_6000861.h5 # TODO: SET.
  path_to_data: /itet-stor/mcrespo/bmicdatasets-originals/Originals/fastMRI/brain/multicoil_train/file_brain_AXT1POST_205_2050021.h5
  n_slices: 3
  with_mask: False
  center_frac: 0.15

dataloader:
  # batch_size: 220_000 
  batch_size: 120_000
  # batch_size: 60000 # NOTE: This is only for pisco training
  pin_memory: False

model:
  id: Siren1
  params:
    coord_dim: 4
    hidden_dim: 512
    L : 10
    n_layers: 8

loss:
  id: MSE
  params:
    gamma: 1 # Scalar value that gets multiplied to the real loss value
    # epsilon: 1.e-10
    # sigma: 1
    # factor: 0.4

optimizer:
  id: Adam
  params:
    lr: 5.e-6 # The dot is necessary, otherwise the parser will mistake this for a string (and not a float).
    # weight_decay: 0.1

scheduler:
  id: StepLR
  params:
    gamma: 0.1
    step_size: 20_000

# Training Process
n_epochs: 2
log_interval: 1
checkpoint_interval: 1000

l_pisco:
  # addpisco: True
  addpisco: False
  E_epoch: 800
  alpha: 1.e-6 # Regularizer for the W
  factor: 0.01 # How much the Lpisco loss gets weighted
  minibatch: 2000
  patch_size: 9

###################################################
# INFORMATION ONLY - NO EFFECT ON RUN
###################################################
# The following section is for documentation purposes only.
# It does not affect the actual behavior of the run.
# These values are used solely for Tensorboard output, to help identify run types.
hparam_info:
  dataset: "all data (except center)"

  observation_type: "test sample"

  coord_encoding: "positional encoding L=15"

  normalization: "divide by .999 abs quantile"
